<a href="https://colab.research.google.com/github/Fedoseevale/Statistica_Homework10/blob/main/Task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Провести дисперсионный анализ для определения того, есть ли различия среднего роста среди взрослых футболистов, хоккеистов и штангистов.
Даны значения роста в трех группах случайно выбранных спортсменов:

Футболисты: 173, 175, 180, 178, 177, 185, 183, 182.

Хоккеисты: 177, 179, 180, 188, 177, 172, 171, 184, 180.

Штангисты: 172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170.

In [8]:
import numpy as np
from scipy import stats

In [4]:
y1 = np.array([173, 175, 180, 178, 177, 185, 183, 182])
y2 = np.array([177, 179, 180, 188, 177, 172, 171, 184, 180])
y3 = np.array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])

In [5]:
y1

array([173, 175, 180, 178, 177, 185, 183, 182])

In [6]:
y2

array([177, 179, 180, 188, 177, 172, 171, 184, 180])

In [7]:
y3

array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])

In [9]:
f = stats.f_oneway(y1, y2, y3)

In [10]:
f

F_onewayResult(statistic=5.500053450812596, pvalue=0.010482206918698694)

Примем уровень статистической значимости alpha = 0,05. 
pvalue > alpha, следовательно **статистически** **значимых различий между трёмя группами спортсменов нет**. 